export const FSC_KEYWORDS: Record<string, string[]> = {
  "1005": ["guns", "artillery", "cannons"],
  "1010": ["guns", "artillery", "weapons"],
  "1015": ["guns", "tank guns", "artillery"],
  "1020": ["guns", "naval guns", "artillery"],
  "1025": ["guns", "large caliber", "artillery"],
  "1030": ["guns", "heavy artillery", "cannons"],
  "1035": ["guns", "artillery", "railroad guns"],
  "1040": ["chemical", "weapons", "decontamination"],
  "1045": ["torpedoes", "launchers", "depth charges"],
  "1055": ["grenades", "rockets", "pyrotechnics"],
  "1075": ["degaussing", "minesweeping", "naval equipment"],
  "1080": ["camouflage", "deception", "nets"],
  "1090": ["weapon parts", "interchangeable", "components"],
  "1095": ["weapons", "ordinance", "military equipment"],
  "1210": ["fire control", "directors", "targeting"],
  "1220": ["fire control", "computing sights", "targeting"],
  "1240": ["optical sights", "range finders", "targeting"],
  "1250": ["stabilization", "fire control", "gun mounts"],
  "1260": ["fire control", "indicators", "designation"],
  "1265": ["fire control", "transmitters", "radar"],
  "1270": ["aircraft", "gunnery", "fire control"],
  "1280": ["aircraft", "bombing", "fire control"],
  "1285": ["fire control", "radar", "tracking"],
  "1287": ["sonar", "underwater", "fire control"],
  "1290": ["fire control", "targeting", "weapons"],
  "1420": ["missiles", "guidance", "ordnance"],
  "1430": ["missiles", "remote control", "guidance"],
  "1440": ["missile launchers", "launch systems", "ordnance"],
  "1450": ["missiles", "handling", "servicing"],
  "1560": ["aircraft", "airframe", "structural"],
  "1610": ["propellers", "aircraft", "propulsion"],
  "1615": ["helicopters", "rotors", "blades"],
  "1620": ["landing gear", "aircraft", "undercarriage"],
  "1630": ["aircraft wheels", "brakes", "tires"],
  "1650": ["hydraulic", "de-icing", "aircraft systems"],
  "1660": ["air conditioning", "pressurization", "aircraft"],
  "1670": ["parachutes", "cargo", "recovery"],
  "1680": ["aircraft parts", "accessories", "components"],
  "1710": ["arresting gear", "barriers", "carrier deck"],
  "1720": ["catapults", "launch equipment", "carrier"],
  "1730": ["ground support", "aircraft servicing", "GSE"],
  "1740": ["airfield trucks", "trailers", "ground support"],
  "1820": ["spacecraft", "satellites", "aerospace"],
  "1830": ["space", "remote control", "ground control"],
  "1840": ["rocket launchers", "space launch", "pad"],
  "1850": ["space", "handling", "servicing"],
  "1860": ["space suits", "survival", "astronaut"],
  "2010": ["marine", "propulsion", "ship engines"],
  "2020": ["rigging", "cables", "marine"],
  "2030": ["winches", "deck machinery", "marine"],
  "2040": ["marine hardware", "hull", "ship fittings"],
  "2050": ["buoys", "navigation", "marine"],
  "2060": ["fishing", "commercial", "nets"],
  "2090": ["marine", "ship", "boat equipment"],
  "2230": ["railroad", "track", "construction"],
  "2240": ["locomotives", "rail cars", "rolling stock"],
  "2250": ["rails", "track", "railroad materials"],
  "2310": ["passenger vehicles", "cars", "automotive"],
  "2320": ["trucks", "heavy duty", "commercial vehicles"],
  "2330": ["trailers", "hauling", "cargo"],
  "2340": ["motorcycles", "bicycles", "scooters"],
  "2410": ["tracked tractors", "crawlers", "earthmoving"],
  "2420": ["wheeled tractors", "agricultural", "farm"],
  "2430": ["high speed", "tracked", "tractors"],
  "2510": ["vehicle body", "cab", "frame"],
  "2520": ["transmission", "drivetrain", "axles"],
  "2530": ["brakes", "wheels", "suspension"],
  "2540": ["vehicle interior", "seats", "accessories"],
  "2541": ["military vehicles", "weapon mounts", "tactical"],
  "2590": ["vehicle parts", "automotive", "components"],
  "2620": ["aircraft tires", "tubes", "pneumatic"],
  "2805": ["gas engines", "reciprocating", "industrial"],
  "2810": ["aircraft engines", "piston", "aviation"],
  "2815": ["diesel", "engines", "heavy equipment"],
  "2820": ["steam engines", "reciprocating", "locomotive"],
  "2825": ["steam turbines", "power generation", "turbines"],
  "2830": ["hydraulic turbines", "water", "hydro power"],
  "2835": ["gas turbines", "industrial", "power"],
  "2840": ["jet engines", "turbofan", "aircraft"],
  "2845": ["rocket engines", "propulsion", "space"],
  "2850": ["rotary engines", "Wankel", "engines"],
  "2895": ["engines", "power plants", "propulsion"],
  "2910": ["fuel systems", "injectors", "pumps"],
  "2915": ["aircraft fuel", "jet fuel", "aviation"],
  "2920": ["electrical", "ignition", "starters"],
  "2925": ["aircraft electrical", "avionics power", "generators"],
  "2930": ["cooling", "radiators", "engine cooling"],
  "2935": ["aircraft cooling", "heat exchangers", "aviation"],
  "2940": ["filters", "oil", "air filters"],
  "2945": ["aircraft filters", "aviation", "lubrication"],
  "2950": ["turbocharger", "supercharger", "boost"],
  "2990": ["engine accessories", "gaskets", "seals"],
  "2995": ["aircraft engine", "accessories", "aviation"],
  "3010": ["torque converters", "transmissions", "drivetrains"],
  "3020": ["gears", "sprockets", "chains"],
  "3030": ["belts", "V-belts", "timing belts"],
  "3040": ["power transmission", "drives", "couplings"],
  "3110": ["ball bearings", "roller bearings", "anti-friction"],
  "3120": ["bushings", "plain bearings", "sleeve"],
  "3130": ["mounted bearings", "pillow blocks", "flange"],
  "3210": ["sawmill", "lumber", "wood processing"],
  "3220": ["woodworking", "machinery", "carpentry"],
  "3230": ["woodworking", "tools", "attachments"],
  "3405": ["saws", "filing", "cutting tools"],
  "3408": ["CNC", "machining centers", "mills"],
  "3410": ["EDM", "electrical discharge", "erosion"],
  "3411": ["boring", "machining", "precision"],
  "3412": ["broaching", "internal", "keyways"],
  "3413": ["drilling", "tapping", "machining"],
  "3414": ["gear cutting", "hobbing", "gears"],
  "3415": ["grinding", "abrasive", "precision"],
  "3416": ["lathes", "turning", "CNC"],
  "3417": ["milling", "machining", "CNC"],
  "3418": ["planers", "shapers", "machining"],
  "3419": ["machine tools", "machining", "metalworking"],
  "3422": ["rolling mills", "drawing", "metal forming"],
  "3424": ["heat treating", "furnaces", "hardening"],
  "3426": ["metal finishing", "plating", "coating"],
  "3431": ["arc welding", "TIG", "MIG"],
  "3432": ["resistance welding", "spot weld", "seam"],
  "3433": ["gas welding", "cutting", "brazing"],
  "3436": ["welding positioners", "manipulators", "automation"],
  "3438": ["welding", "equipment", "fabrication"],
  "3439": ["welding supplies", "rods", "flux"],
  "3441": ["bending", "forming", "press brakes"],
  "3442": ["hydraulic presses", "stamping", "forming"],
  "3443": ["mechanical presses", "stamping", "punching"],
  "3444": ["manual presses", "bench", "hand"],
  "3445": ["punching", "shearing", "cutting"],
  "3446": ["forging", "hammers", "die forging"],
  "3447": ["wire forming", "ribbon", "metal"],
  "3448": ["riveting", "assembly", "fastening"],
  "3449": ["metal forming", "fabrication", "cutting"],
  "3450": ["portable tools", "grinders", "drills"],
  "3455": ["cutting tools", "end mills", "inserts"],
  "3456": ["dies", "punches", "tooling"],
  "3460": ["machine accessories", "chucks", "vises"],
  "3461": ["fixtures", "tooling", "metalworking"],
  "3465": ["jigs", "fixtures", "templates"],
  "3470": ["machine shop", "tool sets", "kits"],
  "3510": ["laundry", "dry cleaning", "textile"],
  "3520": ["shoe repair", "cobbling", "leather"],
  "3530": ["sewing", "industrial", "textile repair"],
  "3540": ["packaging", "wrapping", "conveyors"],
  "3550": ["vending", "coin operated", "machines"],
  "3590": ["service", "trade", "equipment"],
  "3605": ["food processing", "conveyors", "packaging"],
  "3610": ["printing", "bookbinding", "duplicating"],
  "3611": ["marking", "labeling", "industrial"],
  "3615": ["pulp", "paper", "mill equipment"],
  "3620": ["plastics", "rubber", "injection molding"],
  "3625": ["textile", "weaving", "spinning"],
  "3630": ["concrete", "cement", "masonry"],
  "3635": ["glass", "crystal", "optical"],
  "3640": ["tobacco", "cigarettes", "processing"],
  "3645": ["leather", "tanning", "finishing"],
  "3650": ["chemical", "pharmaceutical", "mixing"],
  "3655": ["gas", "dispensing", "cylinders"],
  "3660": ["crushers", "grinders", "size reduction"],
  "3670": ["semiconductor", "PCB", "microelectronics"],
  "3680": ["foundry", "casting", "molds"],
  "3685": ["containers", "metal", "manufacturing"],
  "3690": ["ammunition", "ordnance", "loading"],
  "3693": ["assembly", "automation", "robotics"],
  "3694": ["cleanroom", "laminar flow", "HEPA"],
  "3695": ["industrial", "specialized", "machinery"],
  "3710": ["tilling", "plowing", "soil"],
  "3720": ["harvesting", "combines", "agricultural"],
  "3730": ["dairy", "poultry", "livestock"],
  "3740": ["pest control", "sprayers", "agricultural"],
  "3750": ["gardening", "lawn", "landscaping"],
  "3770": ["saddlery", "harness", "equestrian"],
  "3805": ["excavators", "bulldozers", "earthmoving"],
  "3810": ["cranes", "hoisting", "construction"],
  "3815": ["crane attachments", "buckets", "grapples"],
  "3820": ["mining", "drilling", "rock"],
  "3825": ["snow removal", "sweepers", "road"],
  "3830": ["loader", "backhoe", "attachments"],
  "3835": ["oil", "gas", "petroleum"],
  "3895": ["construction", "equipment", "heavy"],
  "3910": ["conveyors", "material handling", "belts"],
  "3915": ["feeders", "vibratory", "material handling"],
  "3920": ["handling", "forklifts", "pallet jack"],
  "3930": ["warehouse", "forklifts", "electric"],
  "3940": ["block", "tackle", "rigging"],
  "3950": ["winches", "hoists", "cranes"],
  "3960": ["elevators", "escalators", "lifts"],
  "3990": ["material handling", "conveyors", "storage"],
  "4010": ["chain", "wire rope", "cable"],
  "4020": ["rope", "cordage", "synthetic"],
  "4030": ["fittings", "rigging", "hardware"],
  "4110": ["refrigeration", "coolers", "freezers"],
  "4120": ["air conditioning", "HVAC", "cooling"],
  "4130": ["refrigeration parts", "compressors", "evaporators"],
  "4140": ["fans", "blowers", "ventilation"],
  "4150": ["vortex", "cooling", "tubes"],
  "4210": ["firefighting", "extinguishers", "hoses"],
  "4220": ["diving", "lifesaving", "marine"],
  "4230": ["decontamination", "CBRN", "protective"],
  "4235": ["spill", "hazardous", "cleanup"],
  "4240": ["safety", "rescue", "harnesses"],
  "4250": ["recycling", "reclamation", "waste"],
  "4310": ["compressors", "vacuum", "pumps"],
  "4320": ["pumps", "hydraulic", "water"],
  "4330": ["separators", "filters", "centrifugal"],
  "4410": ["boilers", "steam", "industrial"],
  "4420": ["heat exchangers", "condensers", "cooling"],
  "4430": ["furnaces", "ovens", "kilns"],
  "4440": ["dryers", "dehydrators", "drying"],
  "4460": ["air purification", "filters", "ventilation"],
  "4510": ["plumbing", "fixtures", "sinks"],
  "4520": ["heaters", "water heater", "space heating"],
  "4530": ["furnaces", "fuel", "burners"],
  "4540": ["plumbing", "HVAC", "sanitation"],
  "4610": ["water purification", "filters", "treatment"],
  "4620": ["distillation", "water", "marine"],
  "4630": ["sewage", "wastewater", "treatment"],
  "4710": ["pipe", "tube", "conduit"],
  "4720": ["hose", "tubing", "flexible"],
  "4730": ["fittings", "couplings", "adapters"],
  "4810": ["valves", "actuated", "control"],
  "4820": ["valves", "manual", "ball valves"],
  "4910": ["auto shop", "vehicle maintenance", "repair"],
  "4920": ["aviation", "aircraft maintenance", "hangar"],
  "4921": ["torpedoes", "naval", "ordnance"],
  "4923": ["depth charges", "mines", "underwater"],
  "4925": ["ammunition", "ordnance", "loading"],
  "4927": ["rockets", "ordnance", "maintenance"],
  "4930": ["fuel dispensing", "lubrication", "tanks"],
  "4931": ["fire control", "weapons", "maintenance"],
  "4933": ["weapons", "armament", "maintenance"],
  "4935": ["missiles", "guided", "maintenance"],
  "4940": ["maintenance", "repair", "shop equipment"],
  "4960": ["spacecraft", "satellite", "maintenance"],
  "4970": ["guided weapons", "missiles", "maintenance"],
  "5110": ["knives", "cutting", "hand tools"],
  "5120": ["wrenches", "hammers", "hand tools"],
  "5130": ["power tools", "drills", "sanders"],
  "5133": ["drill bits", "countersinks", "cutting"],
  "5136": ["taps", "dies", "threading"],
  "5140": ["tool boxes", "storage", "cabinets"],
  "5180": ["tool kits", "outfits", "specialty"],
  "5210": ["measuring", "calipers", "rulers"],
  "5220": ["gauges", "inspection", "precision"],
  "5280": ["measurement", "tool sets", "calibration"],
  "5305": ["screws", "fasteners", "threaded"],
  "5306": ["bolts", "fasteners", "hex"],
  "5307": ["studs", "fasteners", "threaded"],
  "5310": ["nuts", "washers", "fasteners"],
  "5315": ["nails", "pins", "keys"],
  "5320": ["rivets", "fasteners", "blind"],
  "5325": ["fasteners", "clips", "retainers"],
  "5330": ["gaskets", "packing", "seals"],
  "5331": ["O-rings", "seals", "elastomer"],
  "5335": ["screening", "mesh", "filter"],
  "5340": ["hardware", "brackets", "hangers"],
  "5341": ["brackets", "mounting", "hardware"],
  "5342": ["weapon", "military", "hardware"],
  "5345": ["grinding wheels", "abrasive", "cutting"],
  "5350": ["abrasives", "sandpaper", "polishing"],
  "5355": ["knobs", "handles", "pointers"],
  "5360": ["springs", "coil", "torsion"],
  "5365": ["bushings", "shims", "spacers"],
  "5410": ["prefab", "modular", "buildings"],
  "5411": ["shelters", "tents", "rigid wall"],
  "5419": ["modular", "support", "systems"],
  "5420": ["bridges", "floating", "military"],
  "5430": ["storage tanks", "silos", "containers"],
  "5440": ["scaffolding", "forms", "concrete"],
  "5445": ["towers", "antenna", "communication"],
  "5450": ["prefab", "structures", "modular"],
  "5510": ["lumber", "wood", "timber"],
  "5520": ["millwork", "doors", "trim"],
  "5530": ["plywood", "veneer", "laminate"],
  "5610": ["aggregate", "gravel", "sand"],
  "5620": ["brick", "block", "tile"],
  "5630": ["conduit", "PVC", "pipe"],
  "5640": ["insulation", "drywall", "building"],
  "5650": ["roofing", "siding", "building"],
  "5660": ["fencing", "gates", "barriers"],
  "5670": ["prefab", "building", "components"],
  "5675": ["composite", "lumber", "alternative"],
  "5680": ["construction", "materials", "building"],
  "5805": ["telephone", "telegraph", "communication"],
  "5810": ["encryption", "security", "crypto"],
  "5811": ["cryptographic", "signals", "intelligence"],
  "5815": ["teletype", "facsimile", "fax"],
  "5820": ["radio", "communications", "transceiver"],
  "5821": ["avionics", "aircraft radio", "communication"],
  "5825": ["navigation", "GPS", "radio"],
  "5826": ["airborne", "navigation", "avionics"],
  "5830": ["intercom", "PA", "audio"],
  "5831": ["aircraft", "communication", "intercom"],
  "5835": ["recording", "audio", "sound"],
  "5836": ["video", "recording", "surveillance"],
  "5840": ["radar", "surveillance", "detection"],
  "5841": ["airborne radar", "avionics", "surveillance"],
  "5845": ["sonar", "underwater", "acoustic"],
  "5850": ["laser", "optical", "communication"],
  "5855": ["night vision", "NVG", "infrared"],
  "5860": ["laser", "coherent", "radiation"],
  "5865": ["electronic warfare", "countermeasures", "ECM"],
  "5895": ["communication", "radio", "equipment"],
  "5905": ["resistors", "electrical", "components"],
  "5910": ["capacitors", "electrical", "storage"],
  "5915": ["filters", "networks", "electronic"],
  "5920": ["fuses", "surge", "protection"],
  "5925": ["circuit breakers", "electrical", "safety"],
  "5930": ["switches", "electrical", "relay"],
  "5935": ["connectors", "electrical", "plugs"],
  "5940": ["terminals", "lugs", "connections"],
  "5945": ["relays", "solenoids", "switches"],
  "5950": ["transformers", "coils", "inductors"],
  "5955": ["oscillators", "crystals", "frequency"],
  "5960": ["vacuum tubes", "electron", "amplifiers"],
  "5961": ["semiconductor", "diodes", "transistors"],
  "5962": ["microcircuits", "chips", "integrated"],
  "5963": ["modules", "electronic", "subassemblies"],
  "5965": ["headsets", "microphones", "speakers"],
  "5970": ["insulators", "electrical", "dielectric"],
  "5975": ["electrical", "supplies", "hardware"],
  "5977": ["brushes", "electrodes", "contact"],
  "5980": ["optoelectronic", "LED", "sensors"],
  "5985": ["antennas", "waveguides", "RF"],
  "5990": ["synchros", "resolvers", "position"],
  "5995": ["cable", "harness", "assemblies"],
  "5996": ["amplifiers", "RF", "signal"],
  "5998": ["circuit boards", "PCBs", "electronics"],
  "5999": ["electronic", "components", "miscellaneous"],
  "6005": ["fiber optic", "splitters", "couplers"],
  "6006": ["attenuators", "fiber", "signal"],
  "6007": ["fiber optic", "filters", "optical"],
  "6008": ["multiplexer", "fiber", "optical"],
  "6010": ["fiber optic", "cable", "conductors"],
  "6015": ["fiber optic", "cable", "fiber"],
  "6020": ["fiber optic", "harness", "assembly"],
  "6021": ["fiber optic", "switches", "optical"],
  "6025": ["fiber optic", "transmitters", "optical"],
  "6026": ["fiber optic", "receivers", "optical"],
  "6029": ["repeaters", "fiber", "optical"],
  "6030": ["fiber optic", "devices", "optical"],
  "6032": ["fiber optic", "sources", "detectors"],
  "6033": ["photodetectors", "fiber", "optical"],
  "6034": ["modulators", "fiber", "optical"],
  "6035": ["fiber optic", "image", "transfer"],
  "6040": ["fiber optic", "sensors", "optical"],
  "6050": ["fiber optic", "passive", "splitters"],
  "6060": ["fiber optic", "connectors", "interconnect"],
  "6070": ["fiber optic", "accessories", "supplies"],
  "6080": ["fiber optic", "kits", "sets"],
  "6099": ["fiber optic", "components", "optical"],
  "6105": ["motors", "electric", "AC DC"],
  "6110": ["motor control", "VFD", "drives"],
  "6115": ["generators", "power", "electrical"],
  "6116": ["fuel cells", "hydrogen", "power"],
  "6117": ["solar", "PV", "renewable"],
  "6120": ["transformers", "power", "distribution"],
  "6125": ["converters", "rotating", "electrical"],
  "6130": ["converters", "rectifiers", "inverters"],
  "6135": ["batteries", "primary", "disposable"],
  "6140": ["batteries", "rechargeable", "lithium"],
  "6145": ["wire", "cable", "electrical"],
  "6150": ["power", "distribution", "electrical"],
  "6160": ["batteries", "holders", "fixtures"],
  "6210": ["lighting", "fixtures", "indoor"],
  "6220": ["vehicle", "lights", "automotive"],
  "6230": ["flashlights", "portable", "lighting"],
  "6240": ["lamps", "bulbs", "LED"],
  "6250": ["ballasts", "lampholders", "lighting"],
  "6260": ["lighting", "gas", "nonelectrical"],
  "6310": ["traffic", "signals", "transit"],
  "6320": ["marine", "alarm", "ship"],
  "6330": ["railroad", "signals", "warning"],
  "6340": ["aircraft", "alarm", "avionics"],
  "6350": ["alarm", "security", "detection"],
  "6505": ["pharmaceutical", "drugs", "biological"],
  "6508": ["cosmetics", "toiletries", "medicated"],
  "6510": ["bandages", "dressings", "medical"],
  "6515": ["surgical", "instruments", "medical"],
  "6520": ["dental", "instruments", "equipment"],
  "6525": ["X-ray", "imaging", "radiology"],
  "6530": ["hospital", "furniture", "equipment"],
  "6532": ["scrubs", "gowns", "surgical"],
  "6540": ["ophthalmic", "eye", "optometry"],
  "6545": ["first aid", "med kits", "field"],
  "6550": ["diagnostic", "test kits", "lab"],
  "6605": ["navigation", "compass", "instruments"],
  "6610": ["flight", "instruments", "avionics"],
  "6615": ["autopilot", "gyro", "avionics"],
  "6620": ["engine", "gauges", "instruments"],
  "6625": ["electrical", "test", "measurement"],
  "6630": ["chemical", "analysis", "lab"],
  "6635": ["testing", "inspection", "NDT"],
  "6636": ["environmental", "chambers", "testing"],
  "6640": ["laboratory", "equipment", "lab"],
  "6645": ["timers", "clocks", "measurement"],
  "6650": ["optical", "instruments", "test"],
  "6655": ["geophysical", "seismic", "survey"],
  "6660": ["meteorological", "weather", "instruments"],
  "6665": ["hazard", "detection", "sensors"],
  "6670": ["scales", "balances", "weighing"],
  "6675": ["drafting", "surveying", "mapping"],
  "6680": ["flow", "level", "measurement"],
  "6685": ["pressure", "temperature", "humidity"],
  "6695": ["instruments", "measurement", "test"],
  "6710": ["motion picture", "cameras", "cinema"],
  "6720": ["cameras", "photography", "still"],
  "6730": ["projectors", "photo", "display"],
  "6740": ["photo", "developing", "processing"],
  "6750": ["photo", "supplies", "film"],
  "6760": ["photography", "accessories", "equipment"],
  "6770": ["film", "processed", "archival"],
  "6780": ["photo", "kits", "sets"],
  "6810": ["chemicals", "industrial", "reagents"],
  "6820": ["dyes", "pigments", "coloring"],
  "6830": ["gases", "compressed", "liquefied"],
  "6840": ["pesticides", "disinfectants", "cleaning"],
  "6850": ["chemical", "specialties", "industrial"],
  "6910": ["training", "aids", "education"],
  "6920": ["weapons", "training", "simulators"],
  "6930": ["operation", "training", "simulators"],
  "6940": ["communications", "training", "simulators"],
  "7010": ["ADP", "systems", "computers"],
  "7020": ["analog", "computer", "processing"],
  "7021": ["digital", "computer", "CPU"],
  "7022": ["hybrid", "computer", "processing"],
  "7025": ["storage", "input", "output"],
  "7030": ["software", "ADP", "applications"],
  "7035": ["ADP", "supplies", "peripherals"],
  "7040": ["punched card", "legacy", "data"],
  "7042": ["microcomputer", "controllers", "embedded"],
  "7045": ["ADP", "consumables", "supplies"],
  "7050": ["ADP", "components", "hardware"],
  "7105": ["furniture", "household", "residential"],
  "7110": ["office", "furniture", "desks"],
  "7125": ["cabinets", "shelving", "storage"],
  "7195": ["furniture", "fixtures", "miscellaneous"],
  "7210": ["furnishings", "household", "decor"],
  "7220": ["flooring", "carpet", "tiles"],
  "7230": ["draperies", "awnings", "window"],
  "7240": ["containers", "storage", "utility"],
  "7290": ["household", "commercial", "furnishings"],
  "7310": ["cooking", "baking", "commercial"],
  "7320": ["kitchen", "appliances", "commercial"],
  "7330": ["kitchen", "utensils", "tools"],
  "7340": ["cutlery", "knives", "flatware"],
  "7350": ["tableware", "dishes", "serving"],
  "7360": ["food", "preparation", "kits"],
  "7420": ["calculators", "accounting", "office"],
  "7430": ["typewriters", "composing", "office"],
  "7435": ["office", "information", "systems"],
  "7450": ["dictation", "recording", "office"],
  "7460": ["filing", "visible record", "office"],
  "7490": ["office", "machines", "equipment"],
  "7510": ["office", "supplies", "paper"],
  "7520": ["office", "devices", "accessories"],
  "7530": ["stationery", "forms", "paper"],
  "7540": ["forms", "standard", "paper"],
  "7610": ["books", "pamphlets", "publications"],
  "7630": ["newspapers", "periodicals", "magazines"],
  "7640": ["maps", "atlases", "charts"],
  "7641": ["aeronautical", "mapping", "charts"],
  "7642": ["hydrographic", "maritime", "charts"],
  "7643": ["topographic", "terrain", "maps"],
  "7644": ["digital", "mapping", "GIS"],
  "7650": ["drawings", "specifications", "technical"],
  "7660": ["sheet music", "scores", "publications"],
  "7670": ["microfilm", "archival", "storage"],
  "7690": ["printed", "publications", "matter"],
  "7710": ["musical", "instruments", "band"],
  "7720": ["music", "parts", "accessories"],
  "7730": ["TV", "radio", "entertainment"],
  "7740": ["records", "vinyl", "audio"],
  "7810": ["athletic", "sporting", "sports"],
  "7820": ["games", "toys", "recreation"],
  "7830": ["gym", "recreation", "fitness"],
  "7910": ["floor", "polishers", "cleaning"],
  "7920": ["brooms", "brushes", "cleaning"],
  "7930": ["cleaning", "polishing", "compounds"],
  "8010": ["paints", "varnishes", "coatings"],
  "8020": ["brushes", "paint", "artists"],
  "8030": ["sealants", "preservatives", "waterproofing"],
  "8040": ["adhesives", "glue", "bonding"],
  "8105": ["bags", "sacks", "packaging"],
  "8110": ["drums", "cans", "containers"],
  "8115": ["boxes", "cartons", "crates"],
  "8120": ["cylinders", "gas", "storage"],
  "8125": ["bottles", "jars", "containers"],
  "8130": ["reels", "spools", "winding"],
  "8135": ["packaging", "bulk", "materials"],
  "8140": ["ammunition", "ordnance", "containers"],
  "8145": ["shipping", "storage", "containers"],
  "8305": ["fabric", "textile", "cloth"],
  "8310": ["yarn", "thread", "textile"],
  "8315": ["notions", "findings", "apparel"],
  "8320": ["padding", "stuffing", "upholstery"],
  "8325": ["fur", "pelts", "leather"],
  "8330": ["leather", "hide", "tanning"],
  "8335": ["shoe", "findings", "soling"],
  "8340": ["tents", "tarpaulins", "canvas"],
  "8345": ["flags", "pennants", "banners"],
  "8405": ["outerwear", "men", "jackets"],
  "8410": ["outerwear", "women", "jackets"],
  "8415": ["protective", "clothing", "specialty"],
  "8420": ["underwear", "men", "apparel"],
  "8425": ["underwear", "women", "apparel"],
  "8430": ["footwear", "men", "boots"],
  "8435": ["footwear", "women", "shoes"],
  "8440": ["hosiery", "gloves", "apparel"],
  "8445": ["hosiery", "accessories", "women"],
  "8450": ["children", "infant", "apparel"],
  "8455": ["badges", "insignia", "patches"],
  "8460": ["luggage", "bags", "travel"],
  "8465": ["tactical", "equipment", "field"],
  "8470": ["body armor", "protective", "ballistic"],
  "8475": ["flight", "suits", "aviation"],
  "8510": ["perfumes", "fragrances", "cosmetics"],
  "8520": ["soap", "toiletries", "hygiene"],
  "8530": ["toiletries", "personal", "care"],
  "8540": ["tissue", "paper", "toiletries"],
  "8710": ["feed", "forage", "animal"],
  "8720": ["fertilizers", "agricultural", "soil"],
  "8730": ["seeds", "nursery", "plants"],
  "8810": ["livestock", "food", "animals"],
  "8820": ["animals", "pets", "livestock"],
  "8905": ["meat", "poultry", "fish"],
  "8910": ["dairy", "eggs", "milk"],
  "8915": ["produce", "fruits", "vegetables"],
  "8920": ["bakery", "cereal", "bread"],
  "8925": ["sugar", "candy", "nuts"],
  "8930": ["jams", "jellies", "preserves"],
  "8935": ["soups", "bouillon", "prepared"],
  "8940": ["dietary", "specialty", "nutrition"],
  "8945": ["oils", "fats", "cooking"],
  "8950": ["condiments", "sauces", "spices"],
  "8955": ["coffee", "tea", "beverages"],
  "8960": ["beverages", "soft drinks", "nonalcoholic"],
  "8965": ["alcohol", "beverages", "spirits"],
  "8970": ["rations", "MRE", "composite"],
  "8975": ["tobacco", "cigarettes", "smoking"],
  "9110": ["coal", "solid fuel", "biomass"],
  "9130": ["propulsion", "rocket fuel", "jet"],
  "9140": ["fuel oil", "diesel", "heating"],
  "9150": ["lubricants", "oils", "grease"],
  "9160": ["waxes", "oils", "specialty"],
  "9310": ["paper", "paperboard", "pulp"],
  "9320": ["rubber", "gaskets", "seals"],
  "9330": ["plastics", "fabricated", "materials"],
  "9340": ["glass", "fabricated", "optical"],
  "9350": ["refractories", "fire", "ceramic"],
  "9390": ["composite", "nonmetal", "materials"],
  "9410": ["plant", "materials", "raw"],
  "9420": ["fibers", "textile", "synthetic"],
  "9430": ["animal", "products", "raw"],
  "9440": ["agricultural", "forest", "raw"],
  "9450": ["scrap", "recycling", "nonmetallic"],
  "9505": ["wire", "steel", "ferrous"],
  "9510": ["bars", "rods", "metal"],
  "9515": ["sheet", "plate", "strip"],
  "9520": ["structural", "I-beam", "metal"],
  "9525": ["wire", "copper", "aluminum"],
  "9530": ["bars", "nonferrous", "metal"],
  "9535": ["sheet", "nonferrous", "aluminum"],
  "9540": ["structural", "nonferrous", "aluminum"],
  "9545": ["precious", "gold", "silver"],
  "9610": ["ores", "mining", "minerals"],
  "9620": ["minerals", "natural", "synthetic"],
  "9630": ["additive", "metal", "powder"],
  "9640": ["steel", "iron", "primary"],
  "9650": ["nonferrous", "copper", "aluminum"],
  "9660": ["precious metals", "gold", "silver"],
  "9670": ["scrap", "steel", "recycling"],
  "9680": ["scrap", "nonferrous", "recycling"],
  "9905": ["signs", "displays", "identification"],
  "9910": ["jewelry", "watches", "precious"],
  "9915": ["collectibles", "historical", "antiques"],
  "9920": ["smokers", "lighters", "matches"],
  "9925": ["ecclesiastical", "church", "religious"],
  "9930": ["memorials", "cemetery", "mortuary"],
  "9999": ["miscellaneous", "general", "supplies"],
};
